// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjWVEx8b4F1hw-X2echVvUmW_22MH3mvQ',
    appId: '1:490080356393:web:70d37e5673479d91b73438',
    messagingSenderId: '490080356393',
    projectId: 'restaurante-4c0ce',
    authDomain: 'restaurante-4c0ce.firebaseapp.com',
    storageBucket: 'restaurante-4c0ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2lGf5Tae-3YYaHNFS1-iCM2tLvJoG2_k',
    appId: '1:490080356393:android:a6865f56764b0767b73438',
    messagingSenderId: '490080356393',
    projectId: 'restaurante-4c0ce',
    storageBucket: 'restaurante-4c0ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBKRRSXs8r-gasfq50JIKy89et8joABcw',
    appId: '1:490080356393:ios:d3dbbb35eda06368b73438',
    messagingSenderId: '490080356393',
    projectId: 'restaurante-4c0ce',
    storageBucket: 'restaurante-4c0ce.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBKRRSXs8r-gasfq50JIKy89et8joABcw',
    appId: '1:490080356393:ios:d3dbbb35eda06368b73438',
    messagingSenderId: '490080356393',
    projectId: 'restaurante-4c0ce',
    storageBucket: 'restaurante-4c0ce.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjWVEx8b4F1hw-X2echVvUmW_22MH3mvQ',
    appId: '1:490080356393:web:e4f888c79266aa22b73438',
    messagingSenderId: '490080356393',
    projectId: 'restaurante-4c0ce',
    authDomain: 'restaurante-4c0ce.firebaseapp.com',
    storageBucket: 'restaurante-4c0ce.appspot.com',
  );
}
